### ISSUE TITLE
Server crashes on unsupported HTTP method

### ISSUE THREAD

**Issue by arokor** [nikkiii/embedhttp#16]
To provoke this error:
curl -I -X PUT http://host:port/

Result:
Uncaught Exception java.lang.IllegalArgumentException: PUT is not a constant in org.nikkii.embedhttp.impl.HttpMethod

**Comment by nikkiii** [comment]
To add to this, I've added support for PUT/HEAD/DELETE/etc, and it's up to the handlers to handle these. By default, if it's a HEAD request or an http no content response, EmbedHTTP will ignore the body and close any resources opened.
