### ISSUE TITLE
Server crash on invalid http method

### ISSUE THREAD

**Issue by arokor** [nikkiii/embedhttp#18]
When querying the server with an invalid HTTP method the server now responds with 405 Method not supported but then immediately crashes.

To provoke:
curl -I -X FOO http://10.0.0.21:8888/

**Comment by nikkiii** [comment]
Thanks for reporting this, but your check would assume it has no response body, which could be incorrect. I've pushed a commit to fix this (c4b46613) but forgot to reference this issue.
